services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data_bloglist:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: postgres-bloglist

volumes:
  postgres_data_bloglist:
